CREATE TABLE fotos (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `fecha` DATE DEFAULT NULL,
  `enlace` TEXT DEFAULT NULL,
  `last_updates` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
